blog/urls.py
from django.urls import include,path
from . import views

app_name='blog'

urlpatterns = [
    path('', views.all_blogs, name="all_blogs"),
    path('<int:blog_id>/', views.details, name="details"),

]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

app_name='portfolio'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('blog/', include('blog.urls')),

]
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    
    title = models.CharField(max_length=100)
    desc=models.TextField()
    date=models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title=models.CharField(max_length=100)
    description=models.CharField(max_length=300)
    image=models.ImageField(upload_to='portfolio/images/')
    url=models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog

def all_blogs(request):
    blogs=Blog.objects.all()
    return render(request,'blog/all_blogs.html',{'blogs':blogs})

def details(request, blog_id):
    blogs=get_object_or_404(Blog, pk=blog_id)
    return render(request,'blog/details.html',{'blogs':blogs})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects=Project.objects.all()
    return render(request,'portfolio/home.html',{'projects':projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html'%}
{% load static %}
{% block content %}
<h1 class="alert alert-primary">BLOG</h1>


<h3>Chinmay has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>
{% for blog in blogs %}

<h5>{{ blog.date|date:'M d Y'|upper }}</h5>
<a href="{% url 'blog:details' blog.id %}"><h2>{{ blog.title }}</h2></a>
<p>{{ blog.desc|truncatechars:100 }}</p>

{% endfor %}

{% endblock %}

blog/templates/blog/details.html
{% extends 'portfolio/base.html'%}
{% block content %}
<h2>{{blogs.title}}</h2>
<h3><b>{{blogs.date|date:'F d Y'}}</b></h3>
<p>{{blogs.desc}}</p>
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static "portfolio/logo.png" %}">

    <title>CHINMAY C K</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light alert alert-secondary" role="alert">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="{% static 'portfolio/Resume.pdf' %}">Resume</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.linkedin.com/in/chinmayck/">LinkedIn</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://github.com/chinmayck-github">GitHub</a>
              </li>
              <li>
                <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-info">Blog</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    {% block content %}{% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content %}
{% load static %}
<div >
        <div class="col-5">
        <img src="{% static 'portfolio/hello.jpg' %}" alt="1">
        <br>
    </div>
</div>
<div>
    <div >
      <h1 id="hometext" class="font-weight-bold">Hello there!<br>I am Chinmay C K currently pursuing B.E Computer Science and Engineering. This is my test Website</h1>
    </div>
  </div>

<div class="row">
    {% for project in projects %}
    <div class="col-lg-4 col-md-6">

      {% if project.url %}
      <a href="{{ project.url }}">
        <img src="{{ project.image.url }}" class="img-fluid mb-2">
      </a>
      {% else %}

      <img src="{{ project.image.url }}" class="img-fluid mb-2">
      {% endif %}
      <h3><b>{{ project.title }}</b></h3>
      <p>{{ project.description }}</p>

    </div>
    {% endfor %}
  </div>

  {% endblock %}